### ISSUE TITLE
baseAngleOfLastSegment odd behavior at certain angles

### ISSUE THREAD

**Issue by mrichardsdev** [Falke-Design/PMOrtho#3]
![image](https://user-images.githubusercontent.com/33011308/91582805-aa02dc80-e993-11ea-95d8-46e13944dc2f.png)

I am getting an odd result as seen above. I am guessing it is because the angle is going outside the  -180, 180 range? I have yet to have a look at the code as it is 1am here. Will look into it tomorrow.

**Comment by Falke-Design** [comment]
Can you pls test it again, I updated the code

**Comment by mrichardsdev** [comment]
@Falke-Design Yes, that is working perfectly. Awesome work.

I am going to see if I can make the angle show up on top of the previous point while snapping. May be better to do this in the measure path's plugin instead though.

**Comment by Falke-Design** [comment]
@mike16889 I think this branch is very interesting for you: [angle_tooltip](https://github.com/Falke-Design/PMOrtho/tree/angle_tooltip)

Maybe I work this week more on it but I'm not sure if I finish it. Maybe you can do this and then we can merge it into the master.

- [ ] Option to enable it
- [ ] Translation for Tooltip
- [ ] smoother transition/resizing of the angle-circle between the minium size and the point when it gets bigger because one of the line is bigger then 40% as the other.

**Comment by mrichardsdev** [comment]
@Falke-Design That looks awsome. Way more than I expected.

I had a little play around with leaflet-measure-path last week and came up with this:
![image](https://user-images.githubusercontent.com/33011308/92068147-7982ce80-ede9-11ea-9f88-2786767e75e8.png)

but was unable to get the math right. Things are quite busy at the moment but will take a look when I get a chance.
